# Copyright 2018 Tecnativa - Pedro M. Baeza
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
from datetime import datetime, time, timedelta

from dateutil.relativedelta import relativedelta
from pytz import timezone, utc

from odoo import fields, models


class HrEmployee(models.Model):
    _inherit = "hr.employee"

    theoretical_hours_start_date = fields.Date(
        help="Fill this field for setting a manual start date for computing "
        "the theoretical hours independently from the attendances. If "
        "not filled, employee creation date or the calendar start date "
        "will be used (the greatest of both)."
    )

    def write(self, vals):
        res = super().write(vals)
        # If the theoretical_hours_start_date value is modified and there are attendance
        # records with active=false generated by the cron job, you must delete them to
        # prevent inconsistent data from appearing in the report.
        # We also create any pending attendance that have not been generated
        if "theoretical_hours_start_date" in vals:
            attendance_model = self.env["hr.attendance"].with_context(active_test=False)
            for item in self:
                date_from = (
                    item.theoretical_hours_start_date
                    or fields.Datetime.context_timestamp(item.create_date).date()
                )
                attendance_model.sudo().search(
                    [
                        ("employee_id", "=", item.id),
                        ("active", "=", False),
                        ("check_in", "<", date_from),
                    ]
                ).unlink()
                item._action_create_empty_attendance(
                    date_from, fields.Date.context_today(self)
                )
        return res

    def _action_create_empty_attendance(self, date_from=False, date_to=False):
        """Method for creating inactive attendance records with a
        duration of 0.
        The goal is to prevent the report from having to calculate data
        directly, so employee attendance records are created for past days
        when they should have clocked in."""
        self.ensure_one()
        day_from = datetime.combine(date_from, time.min)
        from_datetime = utc.localize(day_from).astimezone(timezone(self.tz or "UTC"))
        day_to = datetime.combine(date_to, time.max)
        to_datetime = utc.localize(day_to).astimezone(timezone(self.tz or "UTC"))
        items = (
            self.env["hr.attendance"]
            .with_context(active_test=False)
            .search(
                [
                    ("employee_id", "=", self.id),
                    ("check_in", "!=", False),
                    ("check_in", ">=", from_datetime.replace(tzinfo=None)),
                    ("check_in", "<=", to_datetime.replace(tzinfo=None)),
                ]
            )
        )
        # It's important to take both check_in and check_out into account because
        # (although strange) there could be an error where check_in=date1 and
        # check_out=date3; in that case, we don't want to create a record for date2
        # and date3 because they would overlap.
        attendance_dates = sorted(
            {
                fields.Datetime.context_timestamp(
                    attendance, attendance.check_in
                ).date()
                + timedelta(days=i)
                for attendance in items
                if attendance.check_in
                for i in range(
                    (
                        fields.Datetime.context_timestamp(
                            attendance, (attendance.check_out or attendance.check_in)
                        ).date()
                        - fields.Datetime.context_timestamp(
                            attendance, attendance.check_in
                        ).date()
                    ).days
                    + 1
                )
            }
        )
        dates_to_create = {}
        expected_attendances = self.resource_calendar_id._work_intervals_batch(
            from_datetime,
            to_datetime,
            resources=self.resource_id,
            compute_leaves=False,
        )[self.resource_id.id]
        for expected_attendance in expected_attendances:
            expected_attendance_date = expected_attendance[0].date()
            if (
                expected_attendance_date not in attendance_dates
                and expected_attendance_date not in dates_to_create
            ):
                dates_to_create[expected_attendance_date] = expected_attendance
        attendance_vals = []
        for date_to_create in dates_to_create:
            check_in = (
                dates_to_create[date_to_create][0].astimezone(utc).replace(tzinfo=None)
            )
            check_out = check_in + relativedelta(minutes=1)
            attendance_vals.append(
                {
                    "employee_id": self.id,
                    "active": False,
                    "check_in": check_in,
                    "check_out": check_out,
                }
            )
        return self.env["hr.attendance"].create(attendance_vals)
