from . import hr_employee
from . import hr_employee_public
from . import hr_attendance
from . import hr_attendance_break
from . import hr_attendance_break_threshold
from . import hr_attendance_report
from . import hr_attendance_reason
from . import res_config_settings
from . import res_company
