[project]
name = "odoo-addons-oca-hr-attendance"
version = "19.0.20260923.0"
dependencies = [
    "odoo-addon-hr_attendance_employee_calendar_planning==19.0.*",
    "odoo-addon-hr_attendance_reason==19.0.*",
    "odoo-addon-hr_attendance_report_theoretical_time==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
